### ISSUE TITLE
“Invert selection” in comments is broken

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#255]
[Original error msg removed]

**Comment by yellowled** [comment]
I just checked that again (since the original issue was filed in a hurry).

The *Invert Selection* button in *Comments* doesn't do anything. I don't think these come from Bayes, so the original issue title was misleading. It doesn't even throw an errow message for me (Chrome) in the console, but the selection is never inverted.

Still works for i.e. media db, though.

**Comment by ophian** [comment]
> I don't think these come from Bayes, so the original issue title was misleading.

All mine without bayes are working as expected!

**Comment by yellowled** [comment]
Interesting. I have tried it in my productive blog (2.0-rc2) and nbe (fairly git snapshot), both with Chrome and Firefox. Hitting *Invert Selection* does nothing for me in both of them.

**Comment by ophian** [comment]
nbe is not working, since it **has** bayes

**Comment by yellowled** [comment]
That is correct. Apparently, Bayes wraps the whole thing in a fieldset which is done using JS, and that wraps the wrong element, which probably causes the invert selection JS to fail. Already on it. :)

**Comment by yellowled** [comment]
Okay, so the culprit here is definitely `placeSpambutton()` in `bayes_commentlist.js`. I don't understand that code very well, so I'll assign the issue to @onli :)

**Comment by onli** [comment]
The next bayes update should fix this

**Comment by yellowled** [comment]
I'll actually wait for that to come in via Spartacus so I can check on that stray “UPDATE” lang constant I remember seeing there.

**Comment by yellowled** [comment]
@onli You forgot to increment the Bayes version number, which is why Spartacus won't deliver the update. :)

**Comment by onli** [comment]
No, I did that in a second commit. But I pushed into the wrong branch -.-

**Comment by yellowled** [comment]
Fixed that for you :) b395a3364174d2a2473eb0f3e186dbb02825b20a

**Comment by onli** [comment]
I meant the two ;) Now it should work though

**Comment by yellowled** [comment]
Works for me.

**Comment by ophian** [comment]
A 2.0.0. blog with current bayes:
I checked some (not all) entries and tried to submit with "Mark as valid" and nothing happened. Doing it singlewise per entry worked though (except the misexposition thing)

**Comment by yellowled** [comment]
Confirmed, but I'm not sure if/how this is related to the “Invert selection” issue. Might be related to other changes in Spamblock Bayes, though. Seems like `markAllHam()` and `markAllSpam()` don't react. (Don't have time to test this further at the moment, though.)

I'd rather we open a seperate issue for this.

**Comment by onli** [comment]
> I'd rather we open a seperate issue for this.

Please, yes. This is only related in the sense that it might fail because of the layout changes, but not at all the same issue.
