### ISSUE TITLE
Meta-Description gets "lost" constantly

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#577]
I have `serendipity_event_metadesc` installed, using it for adding a custom meta description to all my entries (primarily for sharing in social networks). This meta description gets lost somehow sometimes. Unfortunately I can't reproduce yet when and how that happens, but meanwhile I'm sure it *does* happen.

This has happend for some time (months or years) now. First I thought I just forgot to add a description or didn't save it (just previewing the entry without saving), or that I was imagining things, but for the last weeks I had about a dozen drafts prepared, all with descriptions, and frequently those descriptions were gone when I wanted to publish the drafts. And even though the input for meta description was empty, the former description was still in my browser's form data history - so I'm sure it *had* been saved.

I did not check whether other data affected, and I've got no idea yet what could be related to that data loss, but I'll file this bug now anyway so we can narrow it down together ...

Things I've checked:

* After previewing the entry, everything is still there, even if I don't save again afterwards.
* Adding a new entry does not delete the meta description of other drafts.
* Publishing an entry does not delete the meta description of other drafts.
* As far as I can see, only drafts are affected; published entries are fine.

**Comment by garvinhicking** [comment]
That sounds bad. Maybe you can add logging snippets to he serendipity_updertentry. Log the current state of the vars at all places during the call; then if it ever happens again we maybe can see where it gets lost.

My bet is on an event plugin operating on entryproperties and „draft“ state might also be an offender.

Are you using xmlrpc or other apis by chance? Or just the plain s9y editing interface? Which event plugins are active that listen on the entry-save event hooks?

**Comment by th-h** [comment]
> That sounds bad.

It's a nuisance, more or less, but I can live with it. :-)

> Maybe you can add logging snippets to he serendipity_updertentry. Log the current state of the vars at all places during the call; then if it ever happens again we maybe can see where it gets lost.

Noted. I'll look deeper into that when I have time (which I won't for the next weeks, so I opened this issue now).

> Are you using xmlrpc or other apis by chance? Or just the plain s9y editing interface?

Plain s9y, without any fancy editor plugins, just entering markdown into the default interface.

> Which event plugins are active that listen on the entry-save event hooks?

If that is `backend_save`, then *entryproperties*, *freetag* and *trackback*.

**Comment by garvinhicking** [comment]
With a patch like this (against current master) you should be able to get the proper debugging:

```
diff --git a/include/functions_entries.inc.php b/include/functions_entries.inc.php
index 9f0d1b5f..4a3c6913 100644
--- a/include/functions_entries.inc.php
+++ b/include/functions_entries.inc.php
@@ -1458,6 +1458,10 @@ function serendipity_updertEntry($entry) {
 
     } else {
         /* we need to update */
+        $fp = fopen('/tmp/entryproperties.log', 'w');
+        fwrite($fp, date('Y-m-D H:i') . ' - ' . $_SERVER['REQUEST_URI'] . ' - Updating entry #' . $entry['id'] . "\n");
+        fwrite($fp, "Current entryproperties: " . print_r(serendipity_db_query("SELECT * FROM {$serendipity['dbPrefix']}entryproperties WHERE entryid = " . (int)$entry['id']),1));
+        fclose($fp);
 
         // Get settings from entry if already in DB, which should not be alterable with POST methods
         $_entry            = serendipity_fetchEntry('id', $entry['id'], 1, 1);
@@ -1535,6 +1539,10 @@ function serendipity_updertEntry($entry) {
         serendipity_plugin_api::hook_event('backend_save', $entry, $newEntry);
     }
 
+    $fp = fopen('/tmp/entryproperties.log', 'w');
+    fwrite($fp, "New entryproperties: " . print_r(serendipity_db_query("SELECT * FROM {$serendipity['dbPrefix']}entryproperties WHERE entryid = " . (int)$entry['id']),1));
+    fclose($fp);
+
     if (!serendipity_db_bool($entry['isdraft']) && $entry['timestamp'] <= serendipity_serverOffsetHour()) {
         // Now that plugins are executed, we go ahead into the Temple of Doom and send possibly failing trackbacks.
         // First, original list of references is restored (inside the function call)
```

**Comment by th-h** [comment]
> Patched, many thanks. - We'll see how it goes; since I opened this issue, the problem did not resurface - it figures.

Lost descriptions two or three times. The log did not help much, as it was not appended to, but rewritten each time. `fopen` needs "a", not "w". Should have seen that - never copy & paste without thinking. :)

What I've found after each "loss" of description is

     New entryproperties: 1

in the log. AFAIS that should not happen (?).

Have fixed the debugging code and will keep that monitored.

**Comment by th-h** [comment]
Had no time to check up, but found out that I've lost (most or all) meta description for published articles; so the problem **does** affect all articles, not only drafts, and that is very irritating.

I've got no time currently to dig deeper, but I'll try to get down to that when a little free time comes up.

**Comment by th-h** [comment]
> Had no time to check up, but found out that I've lost (most or all) meta description for published articles; so the problem does affect all articles, not only drafts, and that is very irritating

That seems to be another issue; my "entryproperties" database table is curently nearly empty, and reports a creation date on Jan 13th of this year; that's completely wrong, as this installation dates from 2017 (and the other tables do, too).

**Comment by onli** [comment]
That's irritating. Something else happened to the database? 

Nothing in s9y changed recently in that area that I'm aware of.

**Comment by th-h** [comment]
Most probably user error. *shrug*

Will investigate the earlier issue anyway, as soon as I find time.

**Comment by th-h** [comment]
1. Created a new entry as draft, with a `meta_description`. Publication time was set into the future to **2019-06-03 06:30** (but still saved as a draft).
2. Checked the entry at about 07:00 that day - `meta_description` was gone. I added it again and saved it at 07:04.

Log snippets:
```
###-------
2019-06-03 06:30 - /archives/2159-Wellenreiten-042019.html - Updating entry #2160
Current entryproperties: Array
(   
    [0] => Array
        (   
            [0] => 2160
            [entryid] => 2160
            [1] => meta_description
            [property] => meta_description
            [2] => Wer im Netz unterwegs ist, findet und liest dort so allerlei. Der Linkdump meiner interessanten und spannenden Fundstücke im Mai 2019.
            [value] => Wer im Netz unterwegs ist, findet und liest dort so allerlei. Der Linkdump meiner interessanten und spannenden Fundstücke im Mai 2019.
        )

)
New entryproperties: 1
###-------
2019-06-03 07:04 - /serendipity_admin.php? - Updating entry #2160
Current entryproperties: 1
New entryproperties: Array
(   
    [0] => Array
        (   
            [0] => 2160
            [entryid] => 2160
            [1] => meta_description
            [property] => meta_description
            [2] => Wer im Netz unterwegs ist, findet und liest dort so allerlei. Der Linkdump meiner interessanten und spannenden Fundstücke im Mai 2019.
            [value] => Wer im Netz unterwegs ist, findet und liest dort so allerlei. Der Linkdump meiner interessanten und spannenden Fundstücke im Mai 2019.
        )
)
```

Maybe it's just coincidence, but the description seems to be dropped at publication time (and from viewing a random entry, as it seems).

**Comment by onli** [comment]
At publication time? That reminds me of the delayed trackback sending functionality. It was a plugin of its own once and is now part of `serendipity_event_trackback`. Is that plugin active in your blog?

**Comment by th-h** [comment]
It is active - and there is a call to `serendipity_updertEntry()` in `generateDelayed()` (in `serendipity_event_trackback`). This looks promising.

**Comment by th-h** [comment]
@onli, I think that may really be the culprit.

If there are trackbacks to send, `serendipity_event_trackback.php`, line **289** will trigger:
```
serendipity_updertEntry($stored_entry);
```

`serendipity_updertEntr()` is defined in `include/functions_entries.inc.php`. In line **1468**/**1470**, the hook events _backend_save_ or _backend_publish_ will be triggered.

In `serendipity_event_metadesc.php`, starting at line **230**, `$serendipity['POST']['properties']` will be checked. If `$serendipity['POST']['properties']['meta_description']` is not set (and it won't, as there is no POST request), the `meta_description` property for this entry will be deleted. That seems to be true for all extend properties.

**Comment by onli** [comment]
But it's a bug in the plugin, because there is a check against that, right? In https://github.com/s9y/additional_plugins/blob/d15cc441e0b2f915be28d2bccd78de93be3ba9a0/serendipity_event_metadesc/serendipity_event_metadesc.php#L232

When delayed trackback is called serendipity displays an entry in the frontend, thus `$serendipity['POST']['properties']` should be unset, the plugin should return here and the prior saved properties should stay intact. So I think the bug is there, somehow that POST parameter check fails.

Though that is still manipulable by an attacker. `generateDelayed` in serendipity_event_trackback should remove all POST and GET parameters before calling `serendipity_updertEntry`. But that's a second step.

**Comment by th-h** [comment]
> But it's a bug in the plugin, because there is a check against that, right?

Right. It had been late, yesterday. :)

I'll have to look after that another time, but I think we're on the right track.

(I'm not sure the logic in `serendipity_event_metadesc.php` is right anyway. It checks the new POSTed values against those in the database, and then
- if the property is not in the database, but now set, INSERT it (that is correct)
- if the property in the database is different from the POSTed and the POSTed is not unset, UPDATE it (that seems correct too)
- else: DELETE the property in the database.
But when the property in the database and the POSTed one are identical? Wouldn't that trigger the DELETE clause?)

**Comment by onli** [comment]
> But when the property in the database and the POSTed one are identical? Wouldn't that trigger the DELETE clause?)

Yes! At least that's how it looks like.

And I vaguely remember that we had user reports in the forum in that direction a while ago.

**Comment by th-h** [comment]
I think s9y/additional_plugins#99 should fix that.

**Comment by onli** [comment]
Merged. But this bug remains? Since the initial check does not exit as expected?

**Comment by th-h** [comment]
Not sure, will have to observe. The bug is difficult to reproduce because it seems to appear only unter certain conditions (drafts, plugins, ...). I can't reproduce it with certainty, so I can't really debug it reliably or check wether it is fixed.

I just overlooked the check you pointed out when following the code path. Your idea with the delayed trackback function was promising, but I'm not absolutely sure if that was the culprit.

I will report. (It doesn't help that my blogging frequency went down a lot over the last months ...)

**Comment by th-h** [comment]
It looks like the bugfix for the logic in `serendipity_event_metadesc.php` fixed it for me; had some drafts hang around for about two weeks and didn't lose any description.

I will monitor this for a little bit more and then close the issue.

**Comment by th-h** [comment]
Looks like that was fixed. - Will reopen if it creeps up again.
